### ISSUE TITLE
Plot without dots, i.e. only the line

### ISSUE THREAD

**Issue by ModProg** [Pegacraft/typst-plotting#1]
I want to only plot the line but no the individual points.

I want to move my plot from matplotlib:
![image](https://github.com/Pegacraft/typst-plotting/assets/11978847/2ec26af7-4fd5-4f93-96da-48f07790678d)

To typst:
![image](https://github.com/Pegacraft/typst-plotting/assets/11978847/458b19ed-fde0-4011-9236-22b87dd0d48f)

But have the issue, that the high amount of values creates these dots in the typst-plotting version.

**Comment by Pegacraft** [comment]
For some reason, we completely overlooked this - just made a commit, that adds a feature to support graph plots without the dots. See: 48ec2d685fcc8264dcb5f48d15fd00c4e23e7d8c

**Comment by Pegacraft** [comment]
If you want to use it before the next release - you'd have to use the local version of the lib.
