### ISSUE TITLE
Question: How to use Datetime for Axis

### ISSUE THREAD

**Issue by Sett17** [Pegacraft/typst-plotting#14]
I want to make a graph that shows a cumulative count over time.
The closet thing I could figure out is a cumulative count over the days since the first `datetime`. But that is not really suitable.

```typc
#let data = csv("data/cypress-release.csv").slice(1)
#let dates = data.map(row => str_to_datetime(row.at(0).trim("Z"))).rev()
#let first_date = dates.at(0)
#let day_differences = dates.map(date => int(datetime_day_difference(first_date, date)))
#let x_axis = axis(min: 0, max: day_differences.last(), step: 250, location: "bottom", title: "Days since first release")
#let y_axis = axis(min:0, max: day_differences.len(), step: 10, location: "left", title: "Cumulative release count")
#let enum = day_differences.enumerate()
#let enumT = enum.map(row => (row.at(1), row.at(0)))
#let pl = plot(data: enumT, axes: (x_axis, y_axis))
#graph_plot(pl, (100%, 25%))
// this could probably also be a lot cleaner
```

![Screenshot](https://i.imgur.com/9aICYhQ.png)

I know about the `value` field on the axis, but I don't know how I could get the spacing correct with this.
Is this possible with the current version of this?

**Comment by Gewi413** [comment]
Sadly this currently isn't possible because values are exactly what gets drawn - to allow for not showing every values on an axis, we'd need to change how it gets drawn.
This will become a feature on the next release.

**Comment by Sett17** [comment]
Okay, that makes sense. I'll probably pivot to something else right now, or is there some more or less concrete plan for the release?

**Comment by Sett17** [comment]
Of course :)

Thanks for the great lib
