### ISSUE TITLE
Document that stroke can also define thickness

### ISSUE THREAD

**Issue by ModProg** [Pegacraft/typst-plotting#2]
As `stroke` is used via [`path`](https://typst.app/docs/reference/visualize/path), AFAICT at least for the `graph_plot` there is no reason to not support non-color values, as [`path(stroke)`](https://typst.app/docs/reference/visualize/path/#parameters-stroke) does: 
> [none](https://typst.app/docs/reference/types/none) or [auto](https://typst.app/docs/reference/types/auto) or [length](https://typst.app/docs/reference/types/length) or [color](https://typst.app/docs/reference/types/color) or [dictionary](https://typst.app/docs/reference/types/dictionary) or [stroke](https://typst.app/docs/reference/visualize/line/#parameters-stroke)

I tried with `2pt+blue` and it worked, so probably just a documentation oversight.

**Comment by Pegacraft** [comment]
Updated the docs in 810ebf181339ddcfd6b34b3758b5e406157424da
